version: '3.8'
services:
  # proxy:
  #   build: proxy
  #   ports:
  #     - 80:80
  #   depends_on: 
  #     - backend
  # frontend:
  #   container_name: chiron-frontend
  #   build: front-test-ang-app
  #   networks: 
  #     - back-end-network
  #   ports: 
  #     - 4200:4200
  backend:
    container_name: chiron-backend
    build: back-legs
    secrets: 
      - db-password
    networks:
      - back-end-network
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.27
    container_name: chiron-db
    # image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    networks:
      - back-end-network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=chiron
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chiron-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=chiron-db
    depends_on:
      - chiron-db
    networks:
      - back-end-network
volumes:
  db:
networks:
  back-end-network:
    driver: "bridge"
secrets:
  db-password:
    file: /back-legs/db/db-password.txt
